/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define PERIPH_BASE (0x40000000UL) // Peripherals base address

#define AHB2PERIPH_OFFSET (0x08000000UL) // Offset for AHB2 peripheral bus
#define AHB1PERIPH_OFFSET (0x00020000UL) // Offset for AHB1 peripheral bus

#define AHB2PERIPH_BASE (PERIPH_BASE + AHB2PERIPH_OFFSET) // Base address for AHB2 peripherals
#define AHB1PERIPH_BASE (PERIPH_BASE + AHB1PERIPH_OFFSET) // Base address for AHB1 peripherals

#define GPIOA_OFFSET (0x0000UL)                     // GPIOA offset
#define GPIOA_BASE (AHB2PERIPH_BASE + GPIOA_OFFSET) // GPIOA base address

#define RCC_OFFSET (0x1000UL)                   // Reset and clock control offset
#define RCC_BASE (AHB1PERIPH_BASE + RCC_OFFSET) // RCC base address

#define AHBEN_R_OFFSET (0x14UL)                                             // AHBEN register offset
#define RCC_AHBEN_R (*(volatile unsigned int *)(RCC_BASE + AHBEN_R_OFFSET)) // AHBEN register address

#define MODE_R_OFFSET (0x00UL)                                                // Mode register offset
#define GPIOA_MODE_R (*(volatile unsigned int *)(GPIOA_BASE + MODE_R_OFFSET)) // GPIOA mode register address

#define OD_R_OFFSET (0x14UL)                                              // Output data register offset
#define GPIOA_OD_R (*(volatile unsigned int *)(GPIOA_BASE + OD_R_OFFSET)) // GPIOA output data register address

#define GPIOAEN (1U << 17)  // Bit mask for enabling GPIOA (bit 17)
#define PIN5 (1U << 5)      // Bit mask for GPIOA pin 5
#define LED_PIN PIN5        // Alias for PIN5 representing the LED pin

int main(void)
{
    // Enable clock access to GPIOA
    RCC_AHBEN_R |= GPIOAEN;
    GPIOA_MODE_R |= (1UL << 10);    // Set bit 10 to 1
    GPIOA_MODE_R &= ~(1UL << 11);   // Set bit 11 to 0

    /* Loop forever */
    while (1)
    {
        // Toggle LED on/off
        GPIOA_OD_R ^= LED_PIN;
        for (int i = 0; i < 1000000; i++) {}    // Delay the loop
    }
}
